Makefile
user_l4v previously invoked build_user_l*v4* instead of build_user_l4v
=> Fix target user_l4v in Makefile

l4v.dockerfile, user.dockerfile
Recent commits have led the user_l4v account to be configured with an empty .isabelle dir. 
This pull request restores the way things worked previously, by letting root and user_l4v share the same .isabelle dir: both shall be symlinks to  the /isabelle dir.
=> Fix "make user_l4v"

user.dockerfile
To let  users use additional tools, the way to go is to add lines in extras.dockerfile.
Nevertheless, the process of discovering the tools you need, then terminate the user container, add lines to extras.dockerfile, build a new image and run a new container is very tedious - especially doing that one tool at a time, which is what happens in practice.
So I suggest to let users be sudoers, in order to let them install new tools while using a container, then report them to extras.dockerfile for later use.
To sum up, it's a suggested usability improvement.
=> Let users be sudoers

Makefile, README.md, dockerfiles/user.Dockerfile, scripts/l4v.sh, scripts/utils/user.sh
This is much cleaner for reading and linting, and as such, much easier to add logic to.
In this case, more complex logic on group creation has been added. If group creation fails, we now abandon trying to setup the group, which is mostly a nice-to-have.
I also added a small commit to fix https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/issues/16, which was way easier than previous attempts.
Reporting and testing from: @robs-cse, who conveniently has an OSX box to test on :smile:
=> Migrate logic away from user.Dockerfile into a bash script. 

.github/workflows/linter.yml, scripts/base_tools.sh
It looks like this is not part of the base dependencies any more, but needed by git and repo etc.
=> Explicitly install `ssh`

scripts/base_tools.sh
The container lacks ping / traceroute / ip commands which are useful when debugging network issues. This PR adds them.
Signed-off-by: Thomas Böhm <thomas.boehm@hensoldt-cyber.de>
=> Add basic network troubleshooting tools to the base image

.github/workflows/linter.yml
This should prevent the linter from complaining about the (correct) apply-rush.sh script on every PR.
=> Lint only changed/modified files

dockerfiles/apply-tex.Dockerfile, scripts/apply-tex.sh, scripts/sel4.sh
This commit adds doxygen + sufficient LaTeX dependencies to build the seL4 reference manual.
See also the discussion on seL4/ci-actions#65
=> sel4.sh: add setup for building documentation

scripts/apply-rust.sh
Support for the Rumprun target was removed recently and this is causing
the Rust dockerfile to fail. Note that we don't actually test any of the
Rumprun Rust stuff at all in regression.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> Use rust stable and remove rumprun rust target

scripts/sel4.sh
The latest nanopb tools now use python3 instead of python2 which causes
some of the Bamboo builds to fail. We leave python-protobuf here as the
sel4test manifest which the dockerfiles test against has not yet updated to
the latest changes which include the newest version of nanopb.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> Add python-protobuf3

scripts/l4v.sh
There are no active branches any more that require Isabelle2019, so we don't need to cache these.
This might solve the disk space problem encountered in #46
=> l4v: remove Isabelle2019 components

scripts/camkes.sh
Actually, I wonder if the comment still holds today, that CAmkES has this card-coded. I could not find a a place where this is hard-coded and I've not see any errors with the wrong link either. This symlink came in with 9557742518be15676cac6369e061c83d94315882 from @tcptomato, but neither the commit message nor the PR https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles/pull/14 mentions this part of the change. So, do we have to create this link at all?
=> Delete obsolete clang symlink (instead of updating it to keep strange legacy)

.github/workflows/docker-build.yml, .github/workflows/docker-deploy.yml
This auto-deploys the main docker containers (seL4, camkes, camkes-everything, l4v) to docker on push to master + once a week + on manual trigger.
This means pre-built caches, Google repo version etc should stay up to date automatically now.
When we have seen this working properly for some time, I'm planning to add a trigger for automatically rebuilding the ci-actions containers that are based on these here.
=> github action for auto-deploying docker

.github/workflows/linter.yml
- use checkout action v3 as in super-linter docs
- clone with full history, so that diffs work
- use slim image, because we're not using any of the linters
not present there
This might fix the issues observed in #50
=> github: linter action tweaks

.github/workflows/docker-deploy.yml
Had previously assumed the `latest` tag was automatic, but it turns out it is not.
=> github: update `latest` tag on docker push

scripts/utils/check_for_old_docker_imgs.sh
On NixOS Linux, `make user` fails with:
```bash
$ make user
scripts/utils/check_for_old_docker_imgs.sh
make: scripts/utils/check_for_old_docker_imgs.sh: No such file or directory
make: *** [Makefile:169: run_checks] Error 127
```
This is due to `scripts/utils/check_for_old_docker_imgs.sh` attempting to run bash as its interpreter using a hardcoded `/bin/bash` path. Unfortunately, this doesn't work on NixOS (as well as some other operating systems) for several reasons, one of them being that bash cannot be installed on `/bin`, by design.
This PR changes the interpreter path (the shebang directive) to this instead:
```bash
#!/usr/bin/env bash
```
This is a more portable way to run a bash script and is also recommended by numerous sources, including various Stack Overflow answers and even …
=> Fix shebang to be more portable

.github/workflows/docker-deploy.yml
Forks won't have the necessary secrets set and shouldn't deploy to the trustworthysystems repo in any case.
Fixes #51
=> github: deploy/push only from seL4 org

.github/workflows/docker-build.yml, .github/workflows/docker-deploy.yml
This will hopefully avoid that the underlying GitHub runner runs out of disk space.
=> github: split build into separate jobs

scripts/base_tools.sh
`python-is-python2` provides `python` in apt and installs python2 dependencies, which we no longer need.
See: https://github.com/seL4/docs/pull/188
=> Remove python2 from base_tools.sh

.github/workflows/docker-build.yml, .github/workflows/docker-deploy.yml, .github/workflows/linter.yml
GitHub has started issuing warnings for node16 actions.
=> github: bump action versions to node20

scripts/base_tools.sh
Seems `xxd` is not installed by default, but this is used in `seL4_tools/elfloader-tool/CMakeLists.txt` when`ElfloaderHashInstructions` is enabled. This feature is rarely used and there is no CI coverage also. But when testing https://github.com/seL4/seL4_tools/pull/160 the container gave me an error that `xxd` is not installed.
=> base_tools: add xxd

Makefile, build.sh, dockerfiles/base_tools.Dockerfile
The hope is to reduce image size. This might need further adjustments to explicitly include packages that were implicit before.
=> docker: use -slim base image for debian

scripts/base_tools.sh
Update base snapshot date to make manual builds closer to most recent CI. This should not affect CI builds since these set the snapshot date from the command line.
Eventually CI should bump this automatically after successful deployment.
=> update base snapshot date

.github/workflows/docker-build.yml, Makefile, README.md, build.sh, dockerfiles/apply-binary_decomp.Dockerfile, dockerfiles/apply-cakeml.Dockerfile, dockerfiles/apply-camkes_vis.Dockerfile, dockerfiles/apply-rust.Dockerfile, dockerfiles/apply-sysinit.Dockerfile, dockerfiles/apply-tex.Dockerfile, dockerfiles/base_tools.Dockerfile, dockerfiles/cakeml.Dockerfile, dockerfiles/camkes.Dockerfile, dockerfiles/extras.Dockerfile, dockerfiles/l4v.Dockerfile, dockerfiles/sel4.Dockerfile, dockerfiles/sysinit.Dockerfile, dockerfiles/user.Dockerfile, scripts/camkes.sh, scripts/l4v.sh, scripts/sel4.sh, scripts/utils/user.sh
Building seL4 projects and CAmkES projects should work now. The l4v container will build, but on ARM64 will be missing the `mlton` compiler.
Also includes CI setup (for PRs only for now) and README update.
Both, x64 and arm64 images should be working, but the setup is not yet a full multi-arch build where one container manifest contains both images at the same time. We can do that in a separate step.
=> Add AArch64 container variants

.github/workflows/docker-deploy.yml
Build and deploy multi-arch images for seL4 and CAmkES.
For this PR, `l4v` is staying on x86 only and `camkes-cakeml-rust` is built in both variants, but not yet pushed as multi-arch image.
=> github: build and deploy multi-arch images

Makefile
Mapping /etc/localtime was removed unintentionally in ef7632ca294.
=> Makefile: revert localtime mapping removal

.github/workflows/docker-build.yml, .github/workflows/docker-deploy.yml
Authenticate earlier and unlock MacOS keychain so that the rest of the job can access dockerhub.
=> github: authenticate earlier for Mac deployment

.github/workflows/docker-deploy.yml
Use buildx imagetools to create the multi-arch images without first having to pull them.
=> github: buildx imagetools for multi-arch images

.github/workflows/docker-deploy.yml
- prune old images on self-hosted runner to make sure we're not starting from something stale
- fix typos in arm64/amd64
=> multi-arch: prune old images, fix typo

README.md
With default settings on MacOS it is relatively common to run into "no space left of device" errors when building multiple containers. Add instructions on what to do in those situations.
See also some of the discussion in #40
=> README: instructions for "no space left on device"

scripts/utils/user.sh
The user home is a docker volume, which is persistent between container runs and cannot be mounted during image building.
Store env settings like PATH and other variables in container-global /etc/bash.bashrc instead of user ~/.bashrc so that changes to these variables during image build become visible without deleting the volume.
One example where that is necessary is the recent change to `ghcup` -- those settings don't become visible for users who already have a user-home volume set up.
=> user.sh: put env settings in /etc/bash.bashrc

.github/workflows/docker-deploy.yml
Send a repository-dispatch trigger to the ci-actions repo after deployment is finished, so that the CI containers get rebuilt on the new version.
Should be merged after https://github.com/seL4/ci-actions/pull/356
=> github: send repository-dispatch after deployment

scripts/camkes.sh
ef7632ca29 removed lib32stdc++-10-dev, but it is still needed for the 32bit CamkES Linux VMM.
This should fix #84, although I haven't been able to try it out yet.
=> camkes: re-add lib32stdc++-10-dev

.github/workflows/docker-deploy.yml, README.md, build.sh, dockerfiles/apply-binary_decomp.Dockerfile, dockerfiles/apply-camkes_vis.Dockerfile, dockerfiles/apply-tex.Dockerfile, dockerfiles/base_tools.Dockerfile, dockerfiles/camkes.Dockerfile, dockerfiles/l4v.Dockerfile, dockerfiles/sel4.Dockerfile, scripts/utils/common.sh
- make not using snapshots the default
- remove snapshots from CI build
While the snapshots in theory make the build more reproducible, the snapshot repos is notoriously unreliable in CI making the build fail more often than it succeeds.
Since we publish and tag the CI builds, if somebody wants to use the exact same base containers, they can use the tagged image -- reproducing the image build from scratch is not necessary for that scenario.
=> remove Debian snapshots as default

scripts/base_tools.sh, scripts/sel4.sh
clang-11 is ancient (current is clang-19) and seems to miscompile seL4 in some SMP configurations. Use clang-12 as minimum version instead.
Specifically, the MULTICORE0002 failures on Odroid C4 boards in `ODROID_C4_debug_SMP_MCS_clang_64` configs occur only with clang-11, but not with clang-12, and they do not seem to have any specific cause that is visible in the source.
=> Switch to clang-12 as minimum version

scripts/base_tools.sh, scripts/sel4.sh
The clang-12 experiment did not work out. Not only did it not fix the issue we hoped it would fix, but it also breaks clang RISCV builds, initially because it doesn't find the right `ld`, then because it has trouble with our version of muslibc.
This reverts commit 2c2131ee6da9efb570b93015858696848780b4a6.
=> switch back to clang-11

Makefile
As far as I can tell, `arch` is MacOS-specific. `uname -m` is more portable.
=> Improve portability of arch detection in Makefile
